
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlalihzfrkvfwauksxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bGFsaWh6ZnJrdmZ3YXVrc3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTEyMTYsImV4cCI6MjA2MzYyNzIxNn0.4oXBs0IDPZKOfYk1uzr9e_FStkFHweGfForFddWKJmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
